require 'nokogiri'
require 'open-uri'

require_relative '../lib/DataClass.rb'
require_relative '../lib/Scraper.rb'
require_relative '../lib/Quote.rb'
require_relative '../lib/Author.rb'
require_relative '../lib/CliCommands.rb'
require_relative '../lib/CliTagSearch.rb'
require_relative '../lib/CliQuote.rb'
require_relative '../lib/CliPage.rb'
require_relative '../lib/CliGame.rb'
require_relative '../lib/CLI.rb'